#!/bin/bash

if [ $# -ne 1 ]
then
  echo "Usage: `basename $0` something_i_look_for_in_a_branch_name"
  exit 65
fi
multigit branch -r | \
  grep -i "\(git branch\|$1\)" | \
  grep -v ' -> ' | \
  perl -e 'while(<>){if (!m/^\(/ || $l !~ m/^\(/){print $l}$l = $_}if ($l !~ m/^\(/){print $l}' | \
  sed -e "s/:.*//" | \
  tr -cd [:alnum:][:space:]/._\(\) | \
  sed -e "s/^[^( ]\+//"
